RestaurantReservation/RestaurantReservation/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RestaurantReservation.Data;
using RestaurantReservation.Models;
using RestaurantReservation.ViewModels;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RestaurantReservation.Controllers
{
    [Authorize]
    public class ReservationController : Controller
    {
        public ApplicationDbContext _context { get; }
        public readonly ILogger<Reservation> logger;

        public ReservationController(ApplicationDbContext applicationDbContext, ILogger<Reservation> logger)
        {
            this.logger = logger;
            _context = applicationDbContext;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var model = await _context.Reservations.AsNoTracking().Include(r => r.Table).OrderBy(r => r.ReservationStart).ToListAsync();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Confirm(ReservationViewModel reservationViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            var Table = await _context.Tables.FindAsync(reservationViewModel.TableId);
            if (Table == null)
            {
                return NotFound();
            }
            ViewBag.TableNumber = Table.TableNumber;
            ViewBag.Description = Table.Description;
            return View(reservationViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReservationViewModel reservationVeiwModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Reservation reservation = new Reservation
            {
                ReservationStart = reservationVeiwModel.ReservationStart,
                ReservationEnd = reservationVeiwModel.ReservationEnd,
                NumberOfPeople = reservationVeiwModel.NumberOfPeople,
                TableId = reservationVeiwModel.TableId
            };

            _context.Reservations.Add(reservation);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

RestaurantReservation/RestaurantReservation/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestaurantReservation.Data;
using RestaurantReservation.Models;
using RestaurantReservation.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RestaurantReservation.Controllers
{
    [Authorize]
    public class TableController : Controller
    {
        public ApplicationDbContext _context { get; }

        public TableController(ApplicationDbContext applicationDbContext)
        {
            // constructor injection to inject DbCotnext
            _context = applicationDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await _context.Tables.AsNoTracking().OrderBy(t => t.TableNumber).ToListAsync();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TableCreateViewModel tableCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                Table newTable = new Table
                {
                    TableNumber = tableCreateViewModel.TableNumber,
                    NumberOfSeats = tableCreateViewModel.NumberOfSeats,
                    Description = tableCreateViewModel.Description
                };

                _context.Tables.Add(newTable);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index"); 
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var table = await _context.Tables.FindAsync(id);
            if (table == null)
            {
                return NotFound();
            }
            var tableViewModel = new TableEditViewModel
            {
                Id = table.TableId,
                TableNumber = table.TableNumber,
                Description = table.Description,
                NumberOfSeats = table.NumberOfSeats
            };
            return View(tableViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TableEditViewModel tableEditViewModel)
        {
            if (ModelState.IsValid)
            {
                Table oldTable = await _context.Tables.FindAsync(tableEditViewModel.Id);
                if (oldTable == null)
                {
                    return NotFound();
                }

                oldTable.TableNumber = tableEditViewModel.TableNumber;
                oldTable.NumberOfSeats = tableEditViewModel.NumberOfSeats;
                oldTable.Description = tableEditViewModel.Description;

                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var table = await _context.Tables.FindAsync(id);
            if (table == null)
            {
                return NotFound();
            }
            _context.Tables.Remove(table);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> FindAvailableTables(ReservationViewModel reservationViewModel)
        {
            if (ModelState.IsValid)
            {
                var AllAvailableTables = await _context.Tables
                     .AsNoTracking()
                     .Where(t => t.NumberOfSeats >= reservationViewModel.NumberOfPeople)
                     .Where(t => !_context.Reservations
                                     .Any(r => r.Table.TableId == t.TableId && (
                                                 (reservationViewModel.ReservationStart < r.ReservationStart && r.ReservationStart < reservationViewModel.ReservationEnd)
                                                  ||
                                                 (reservationViewModel.ReservationStart > r.ReservationStart && r.ReservationEnd > reservationViewModel.ReservationStart) )
                                         )
                            )
                     .ToListAsync();
                return PartialView("TablesPartial", AllAvailableTables);
            }
            return BadRequest();
        }
    }
}

RestaurantReservation/RestaurantReservation/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantReservation</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"/>
    @RenderSection("pageCSS", required: false)
</head>
<body class="d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantReservation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Index">Tables</a>
                            </li>
                            <li li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="Account">
                                    <button type="submit" class="nav-link btn-link py-0" style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="flex-grow-1 d-flex flex-column">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="flex-grow-1 d-flex flex-column">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - RestaurantReservation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>